const loginPage = document.getElementById('loginPage');
const dashboardPage = document.getElementById('dashboardPage');
const loginForm = document.getElementById('loginForm');
const loginError = document.getElementById('loginError');
const loginId = document.getElementById('loginId');
const loginPassword = document.getElementById('loginPassword');

const locations = {
  '영도구': [{name:'태종대 방파제', location:'부산광역시 영도구 동삼동', risk:'주의', rain:'0.0', wind:'7.2', windNote:'남동풍', wave:'1.1', waveNote:'보통', zone:'너울성 파도 주의 구역', zoneText:'방파제 끝단 80m 구간은 기상 악화 시 출입이 통제될 수 있습니다.', cctv:'04'}, {name:'절영해안 산책로',location:'부산광역시 영도구 영선동',risk:'안전',rain:'0.0',wind:'4.5',windNote:'남풍',wave:'0.5',waveNote:'낮음',zone:'출입 주의 구역',zoneText:'해안 산책로 일부 구간은 미끄럼 사고에 유의하세요.',cctv:'03'}],
  '해운대구': [{name:'미포 방파제',location:'부산광역시 해운대구 중동',risk:'주의',rain:'0.2',wind:'8.4',windNote:'동풍',wave:'1.4',waveNote:'다소 높음',zone:'낚시 금지 구역',zoneText:'방파제 끝단 50m 구간은 안전시설 점검으로 출입 금지입니다.',cctv:'05'}],
  '기장군': [{name:'대변항 방파제',location:'부산광역시 기장군 기장읍',risk:'안전',rain:'0.0',wind:'3.6',windNote:'북서풍',wave:'0.4',waveNote:'낮음',zone:'주의 구역 없음',zoneText:'현재 별도 통제 구역은 없습니다. 안전수칙을 지켜주세요.',cctv:'03'}],
  '서구': [{name:'송도 방파제',location:'부산광역시 서구 암남동',risk:'경계',rain:'1.1',wind:'12.1',windNote:'북동풍',wave:'2.0',waveNote:'높음',zone:'강풍·고파도 통제 구역',zoneText:'기상 특보로 전 구간 출입이 통제되고 있습니다.',cctv:'04'}]
};
let currentDistrict = '영도구'; let currentPier = 0;
const alerts = [{type:'warning',title:'안전모 미착용 감지',text:'태종대 방파제 CCTV 02 · 출입자 1명',time:'방금 전'},{type:'info',title:'기상 정보 갱신',text:'풍속 7.2m/s, 파고 1.1m 관측',time:'2분 전'},{type:'danger',title:'위험 구역 접근 감지',text:'끝단 통제선 인근 인원 감지',time:'8분 전'}];

function renderLocations(){ const root=document.getElementById('districtList'); root.innerHTML=Object.keys(locations).map(d=>`<div><button class="district ${d===currentDistrict?'active':''}" data-district="${d}">${d}<span>${d===currentDistrict?'⌃':'⌄'}</span></button>${d===currentDistrict?`<div class="pier-list">${locations[d].map((p,i)=>`<button class="pier ${i===currentPier?'active':''}" data-pier="${i}">● ${p.name}</button>`).join('')}</div>`:''}</div>`).join(''); root.querySelectorAll('.district').forEach(b=>b.onclick=()=>{currentDistrict=b.dataset.district;currentPier=0;renderLocations();updateDashboard()}); root.querySelectorAll('.pier').forEach(b=>b.onclick=()=>{currentPier=+b.dataset.pier;renderLocations();updateDashboard()}); }
function updateDashboard(){const p=locations[currentDistrict][currentPier]; document.getElementById('districtName').textContent=currentDistrict;document.getElementById('pierName').textContent=p.name;document.getElementById('pierLocation').textContent=p.location;document.getElementById('riskValue').textContent=p.risk;document.getElementById('rainValue').innerHTML=`${p.rain} <em>mm</em>`;document.getElementById('windValue').innerHTML=`${p.wind} <em>m/s</em>`;document.getElementById('windNote').textContent=p.windNote;document.getElementById('waveValue').innerHTML=`${p.wave} <em>m</em>`;document.getElementById('waveNote').textContent=p.waveNote;document.getElementById('cctvValue').innerHTML=`${p.cctv} <em>/ ${p.cctv}</em>`;document.getElementById('zoneTitle').textContent=p.zone;document.getElementById('zoneText').textContent=p.zoneText;document.getElementById('mapPierLabel').textContent=p.name;document.getElementById('zoneBadge').textContent=p.zone==='주의 구역 없음'?'정상':'1개 구역';}
function renderAlerts(){document.getElementById('alertList').innerHTML=alerts.map(a=>`<div class="alert ${a.type}"><div class="alert-top"><b>${a.title}</b><time>${a.time}</time></div><p>${a.text}</p></div>`).join('')}
function showDashboard(){loginPage.classList.add('fade-out');setTimeout(()=>{loginPage.classList.add('hidden');loginPage.classList.remove('fade-out');dashboardPage.classList.remove('hidden');dashboardPage.animate([{opacity:0,transform:'translateY(8px)'},{opacity:1,transform:'translateY(0)'}],{duration:450,easing:'ease-out'});},430)}
function showLogin(){dashboardPage.classList.add('hidden');loginId.value='';loginPassword.value='';loginError.textContent='';loginPage.classList.remove('hidden');loginPage.animate([{opacity:0},{opacity:1}],{duration:350});loginId.focus()}
loginForm.addEventListener('submit',e=>{e.preventDefault();if(loginId.value==='admin'&&loginPassword.value==='1234'){showDashboard()}else{loginError.textContent='ID 또는 비밀번호가 올바르지 않습니다.';loginForm.classList.remove('shake');void loginForm.offsetWidth;loginForm.classList.add('shake')}});
document.getElementById('userMenuButton').onclick=()=>{const m=document.getElementById('userMenu'),b=document.getElementById('userMenuButton');m.classList.toggle('hidden');b.setAttribute('aria-expanded',!m.classList.contains('hidden'))};
document.getElementById('logoutButton').onclick=showLogin; document.addEventListener('click',e=>{if(!e.target.closest('.user-area'))document.getElementById('userMenu').classList.add('hidden')});
function tick(){document.getElementById('clock').textContent=new Date().toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false})}tick();setInterval(tick,1000);renderLocations();renderAlerts();
